add default value for proxy_from_env
Otherwise aiohttp will raise this
```
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 94, in __init__
    self.update_proxy(proxy, proxy_auth)
TypeError: update_proxy() missing 1 required positional argument: 'proxy_from_env'
```